### ISSUE TITLE
where is HomeSwitch 4?

### ISSUE THREAD

**Issue by yukebrillianth** [TobleMiner/T41-USB-C-PSU#1]

**Comment by TobleMiner** [comment]
Not quite the repo for it but I think I just did not make that one public. Let me see

**Comment by TobleMiner** [comment]
Here you go: https://github.com/TobleMiner/OpenHomelabSwitch

No documentation yet really but if you want to have a peek you can :)

**Comment by yukebrillianth** [comment]
Thank You!
